# Copyright Huawei Technologies Co., Ltd. 2024-2025. All rights reserved.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.npuDevicePlugin.name }}-daemonset
  namespace: {{ .Values.basic.namespace }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.npuDevicePlugin.name }}
  {{- with .Values.updateStrategy }}
  updateStrategy:
    {{- toYaml . | indent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        name: {{ .Values.npuDevicePlugin.name }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      {{- with .Values.npu.nodeSelector }}
      nodeSelector:
        {{- toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      hostPID: true
      {{- if .Values.devicePluginName }}
      serviceAccountName: {{ .Values.devicePluginName }}-service-account
      {{- end }}
      containers:
      - name: npu-device-plugin
        image: {{ .Values.basic.swr_addr }}/{{ .Values.npuDevicePlugin.image.name }}:{{ .Values.npuDevicePlugin.image.version }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args:
        - --device-split-count={{ .Values.deviceSplitCount }}
        - --logging-console={{ .Values.loggingConsole }}
        securityContext:
          privileged: true
        {{- with .Values.flavor.npu_device_plugin_daemonset }}
        resources:
          {{- toYaml . | indent 10 }}
        {{- end }}
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: LD_LIBRARY_PATH
          value: /usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: etc-xpu
          mountPath: /etc/xpu
        - name: cgroup
          mountPath: /sys/fs/cgroup
          readOnly: true
        - name: hostproc
          mountPath: /hostproc
          readOnly: true
        - name: xpu-log
          mountPath: /var/log/xpu
        - name: xpu-sock
          mountPath: /var/lib/xpu
        - name: ascend
          mountPath: /usr/local/Ascend
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: etc-xpu
        hostPath:
          path: /etc/xpu
          type: DirectoryOrCreate
      - name: cgroup
        hostPath:
          type: Directory
          path: /sys/fs/cgroup
      - name: hostproc
        hostPath:
          type: Directory
          path: /proc
      - name: xpu-log
        hostPath: